import {questions,words,randomQuestions} from './questions.js';
import {createFarm} from './scene.js';
const $=id=>document.getElementById(id);let farm;
try{farm=createFarm()}catch(e){$('render-error').hidden=false;$('render-error').textContent='無法啟動 3D。請以支援 WebGL 的 Chrome／Edge 開啟，並確認硬體加速已啟用。';$('start').disabled=true;console.error(e)}
let state='menu',previous='',deck=[],index=0,scores=[],attempts=0,records=[],muted=false,choices=[],teamCount=2,showText=true;
const names=['向日葵隊','小河隊','橡樹隊','草莓隊'];
let activeAudio=null,audioGeneration=0;
const audioMap=fetch('./audio/manifest.json').then(r=>r.json()).then(m=>new Map(m.entries.filter(e=>e.status==='ready').map(e=>[e.text,e.file]))).catch(()=>new Map());
function stopSpeech(){audioGeneration++;if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null}}
async function speak(text){stopSpeech();const generation=audioGeneration;$('audio-status').textContent='';if(muted)return;const map=await audioMap;if(generation!==audioGeneration)return;const path=map.get(text);if(!path){$('audio-status').textContent='此句音檔尚未備妥，請老師朗讀。';$('question').textContent=deck[index]?.prompt||text;return}const audio=new Audio(path);activeAudio=audio;try{await audio.play()}catch{if(generation===audioGeneration){$('audio-status').textContent='音檔播放失敗，請按重播，或由老師朗讀。';$('question').textContent=deck[index]?.prompt||text;}}}
function panel(id){for(const x of ['menu','play','results'])$(x).hidden=x!==id}
function scoreBoard(){const team=index%teamCount;$('scores').replaceChildren(...scores.map((s,i)=>{const e=document.createElement('span');e.className='score'+(i===team?' active':'');e.textContent=`${names[i]} ${s} ★`;return e}));$('turn').textContent=`${names[team]} · 請派代表`}
function start(custom){stopSpeech();teamCount=Number($('teams').value);showText=$('hints').value==='show';deck=custom||($('mode').value==='random'?randomQuestions(Number($('rounds').value)):questions.slice(0,Number($('rounds').value)));index=0;scores=Array(teamCount).fill(0);records=[];document.body.classList.remove('paused');farm?.pause(false);panel('play');load()}
function load(){state='playing';attempts=0;stopSpeech();$('pause').textContent='暫停';$('feedback').textContent='';$('next').hidden=true;$('skip-speech').hidden=true;$('instruction').textContent='一起數一數，再請代表選答案。';const q=deck[index];$('question').textContent=(showText||muted)?q.prompt:'仔細聽：問了哪些動物？';$('source').textContent=q.extension?`教材延伸：V4 第 10–11 頁句型 · 隨機數量`:`教材：V4 第 ${q.source.page} 頁 · 第 ${q.source.item} 題`;$('progress').textContent=`救援進度 ${index+1} / ${deck.length}`;scoreBoard();farm?.populate(q.animal,q.count);
 const alternatives=Array.from({length:10},(_,i)=>i+1).filter(n=>n!==q.count).sort((a,b)=>Math.abs(a-q.count)-Math.abs(b-q.count));choices=[q.count,...alternatives.slice(0,2)];const rotate=(index+1)%3;choices=choices.slice(rotate).concat(choices.slice(0,rotate));$('answers').replaceChildren(...choices.map((n,i)=>{const b=document.createElement('button');b.dataset.value=n;b.setAttribute('aria-label',`${n} ${words[n]}`);b.innerHTML=`${n}<small>${words[n]}</small><small class="key">按鍵 ${i+1}</small>`;b.onclick=()=>answer(n);return b}));speak(q.spokenPrompt)}
function answer(n){if(state!=='playing')return;attempts++;const q=deck[index];if(n!==q.count){$('feedback').textContent='再看仔細一點，一起數一次！';$('instruction').textContent='可以轉動牧場，找找是否漏數。';return}state='feedback';scores[index%teamCount]++;records.push({id:q.id,firstCorrect:attempts===1,attempts,spoken:false,team:index%teamCount});scoreBoard();for(const b of $('answers').children)b.disabled=true;$('feedback').textContent=q.answer;$('instruction').textContent='全隊一起說這句！老師聽完後再前進。';$('next').hidden=false;$('skip-speech').hidden=false;farm?.celebrate();speak(q.answer)}
function next(spoken){if(state!=='feedback')return;records[records.length-1].spoken=spoken;stopSpeech();index++;if(index<deck.length)load();else finish()}
function finish(){state='results';panel('results');$('progress').textContent='本輪救援完成';const correct=records.filter(r=>r.firstCorrect).length;$('report').replaceChildren();for(const text of [`完成 ${records.length} 題救援`,`首次答對 ${correct} / ${records.length}（${Math.round(correct/records.length*100)}%）`,`老師確認跟讀 ${records.filter(r=>r.spoken).length} 題`,...scores.map((s,i)=>`${names[i]}：${s} 顆合作星`)]){const p=document.createElement('p');p.textContent=text;$('report').append(p)}$('review').disabled=records.every(r=>r.firstCorrect)}
function togglePause(){if(!['playing','feedback','paused'].includes(state))return;if(state==='paused'){state=previous;farm?.pause(false);document.body.classList.remove('paused');$('pause').textContent='暫停';$('question').textContent=(showText||muted)?deck[index].prompt:'仔細聽：問了哪些動物？';$('feedback').textContent=state==='feedback'?deck[index].answer:''}else{previous=state;state='paused';stopSpeech();farm?.pause(true);document.body.classList.add('paused');$('pause').textContent='繼續';$('question').textContent='休息一下，等老師說開始。';$('feedback').textContent='已暫停'}for(const b of $('answers').children)b.disabled=state!=='playing';$('next').disabled=state==='paused';$('skip-speech').disabled=state==='paused'}
function menu(){state='menu';stopSpeech();document.body.classList.remove('paused');farm?.pause(false);panel('menu');$('progress').textContent='V4 · Lesson 4 · p.10–11';$('next').disabled=false;$('skip-speech').disabled=false;farm?.populate('pig',7)}
$('start').onclick=()=>start();$('next').onclick=()=>next(true);$('skip-speech').onclick=()=>next(false);$('again').onclick=menu;$('restart').onclick=menu;$('review').onclick=()=>{const ids=new Set(records.filter(r=>!r.firstCorrect).map(r=>r.id));start(deck.filter(q=>ids.has(q.id)))};$('replay').onclick=()=>{if(['playing','feedback'].includes(state))speak(deck[index].spokenPrompt)};$('pause').onclick=togglePause;$('mute').onclick=()=>{muted=!muted;stopSpeech();$('mute').textContent=`語音：${muted?'關':'開'}`;$('mute').setAttribute('aria-pressed',String(muted));if(muted&&!showText&&state==='playing')$('question').textContent=deck[index].prompt};$('left').onclick=()=>farm?.rotate(-.18);$('right').onclick=()=>farm?.rotate(.18);$('homeview').onclick=()=>farm?.resetView();$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('fullscreen').textContent='請按 F11 全螢幕'}};
document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['1','2','3'].includes(e.key))answer(choices[Number(e.key)-1]);if(e.key.toLowerCase()==='r')$('replay').click();if(e.key.toLowerCase()==='p')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','feedback'].includes(state))togglePause()});
// Read-only diagnostics for classroom support and reproducible QA.
window.render_game_to_text=()=>JSON.stringify({state,index,total:deck.length,question:deck[index]?.id,scores,records,scene:farm?.stats()});
